apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  namespace: platform
data:
  alert-rules.yaml: |
    groups:
    - name: api-alerts
      rules:
      # 5xx Error Spike Alert
      - alert: APIHigh5xxErrorRate
        expr: |
          (
            sum by (service) (rate(http_requests_total{status=~"5.."}[5m]))
            /
            sum by (service) (rate(http_requests_total[5m]))
          ) > 0.05  # Alert if more than 5% of requests are 5xx errors
        for: 2m
        labels:
          severity: critical
          category: api
        annotations:
          summary: "High 5xx error rate detected for {{ $labels.service }}"
          description: "The service {{ $labels.service }} has experienced {{ $value | humanize }} error rate over the last 5 minutes"
      
      # Pod Crash Loop Alert
      - alert: PodCrashLooping
        expr: |
          max_over_time(kube_pod_container_status_restarts_total{namespace="platform",pod=~"multitenant-api.*"}[10m])
          - min_over_time(kube_pod_container_status_restarts_total{namespace="platform",pod=~"multitenant-api.*"}[10m])
          > 3  # Alert if pod has restarted more than 3 times in 10 minutes
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value }} times in the last 10 minutes"
      
      # DB Connections Exhausted Alert
      - alert: DBConnectionsExhausted
        expr: |
          (
            pgxpool_connections{pool="default", namespace="platform"}
            /
            pgxpool_max_connections{pool="default", namespace="platform"}
          ) > 0.9  # Alert if more than 90% of connections are in use
        for: 3m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "Database connections exhausted for {{ $labels.pool }}"
          description: "Database pool {{ $labels.pool }} has {{ $value | humanize }}% connections in use"
    
    - name: infrastructure-alerts
      rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanize }}% on {{ $labels.instance }}"
      
      # High Memory Usage
      - alert: HighMemoryUsage
        expr: |
          (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) 
          / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanize }}% on {{ $labels.instance }}"
      
      # Pod Down Alert
      - alert: PodNotReady
        expr: kube_pod_status_ready{namespace="platform",pod=~"multitenant-api.*",condition="true"} == 0
        for: 5m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Pod {{ $labels.pod }} is not ready"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been not ready for more than 5 minutes"
      
      # API Latency Alert
      - alert: APILatencyHigh
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
          category: api
        annotations:
          summary: "API latency is high"
          description: "95th percentile of API latency is {{ $value }} seconds"