# Resource Quotas Configuration
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-prod
  namespace: platform
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "20"
    replicationcontrollers: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: platform
spec:
  hard:
    requests.storage: 100Gi
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: platform
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 50m
      memory: 64Mi
    maxLimitRequestRatio:
      cpu: 4
      memory: 2
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: platform
spec:
  limits:
  - type: Pod
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 100m
      memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: platform
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: platform
spec:
  hard:
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"
    count/daemonsets.apps: "5"
    count/services: "20"
    count/secrets: "50"
    count/configmaps: "50"
    count/ingresses.networking.k8s.io: "10"
    count/jobs.batch: "10"
    count/cronjobs.batch: "5"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: multitenant-api-pdb
  namespace: platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: multitenant-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quota-monitoring-config
  namespace: platform
data:
  monitoring-config.yaml: |
    # Configuration for quota monitoring
    checks:
      - name: "CPU Quota Utilization"
        query: "sum(kube_pod_container_resource_requests_cpu_cores{namespace='platform'}) / sum(kube_resourcequota{namespace='platform', resource='requests.cpu', type='hard'})"
        threshold: 0.8
        alert: "CPU quota utilization is above 80%"
      - name: "Memory Quota Utilization"
        query: "sum(kube_pod_container_resource_requests_memory_bytes{namespace='platform'}) / sum(kube_resourcequota{namespace='platform', resource='requests.memory', type='hard'})"
        threshold: 0.8
        alert: "Memory quota utilization is above 80%"
      - name: "Pod Count Utilization"
        query: "sum(kube_resourcequota_used{namespace='platform', resource='pods'}) / sum(kube_resourcequota{namespace='platform', resource='pods', type='hard'})"
        threshold: 0.9
        alert: "Pod quota utilization is above 90%"